export default {
    "0x1": {
        netName: "ETHEREUM MAINNET",
        symbol: "ETH",
        blockExplorer: "https://etherscan.io",
    },
    "0x5": {
        netName: "GOERLI TESNET",
        symbol: "ETH",
        blockExplorer: "https://goerli.etherscan.io",
    },
    "0x38": {
        netName: "Binance Smart Chain Mainnet",
        jsonRPC: "https://bsc-dataseed1.binance.org",
        chainId: 56,
        symbol: "BNB",
        blockExplorer: "https://bscscan.com",
    },
    "0x61": {
        netName: "Binance Smart Chain Testnet",
        jsonRPC: "https://data-seed-prebsc-1-s1.binance.org:8545",
        chainId: 97,
        symbol: "tBNB",
        blockExplorer: "https://testnet.bscscan.com",
    },
    "0x89": {
        netName: "Polygon Mainnet",
        jsonRPC: "https://polygon-rpc.com/",
        chainId: 89,
        symbol: "MATIC",
        blockExplorer: "https://polygonscan.com",
    },
    "0x13881": {
        netName: "Mumbai",
        jsonRPC: "https://matic-mumbai.chainstacklabs.com",
        chainId: 13881,
        symbol: "MATIC",
        blockExplorer: "https://mumbai.polygonscan.com",
    },
    "0xa86a": {
        netName: "Avalanche C-Chain",
        jsonRPC: "https://api.avax.network/ext/bc/C/rpc",
        chainId: 43114,
        symbol: "AVAX",
        blockExplorer: "https://snowtrace.io",
    },
    "0xa869": {
        netName: "Avalanche Fuji Testnet",
        jsonRPC: "https://api.avax-test.network/ext/bc/C/rpc",
        chainId: 43113,
        symbol: "AVAX",
        blockExplorer: "https://testnet.snowtrace.io",
    },
    "0xfa": {
        netName: "Fantom Opera",
        jsonRPC: "https://rpc.ftm.tools",
        chainId: 250,
        symbol: "FTM",
        blockExplorer: "https://ftmscan.com",
    },
    "0xfa2": {
        netName: "Fantom Testnet",
        jsonRPC: "https://rpc.testnet.fantom.network",
        chainId: 4002,
        symbol: "FTM",
        blockExplorer: "https://testnet.ftmscan.com",
    },
}