export default {
    1: {
        netName: "ETHEREUM MAINNET",
        blockExplorer: "https://etherscan.io",
    },
    5: {
        netName: "GOERLI TESNET",
        blockExplorer: "https://goerli.etherscan.io",
    },
    38: {
        netName: "Binance Smart Chain Mainnet",
        jsonRPC: "https://bsc-dataseed1.binance.org",
        chainId: 38,
        symbol: "BNB",
        blockExplorer: "https://bscscan.com",
    },
    61: {
        netName: "Binance Smart Chain Testnet",
        jsonRPC: "https://data-seed-prebsc-1-s1.binance.org:8545",
        chainId: 61,
        symbol: "tBNB",
        blockExplorer: "https://testnet.bscscan.com",
    },
    89: {
        netName: "Polygon Mainnet",
        jsonRPC: "https://polygon-rpc.com/",
        chainId: 89,
        symbol: "MATIC",
        blockExplorer: "https://polygonscan.com",
    },
    13881: {
        netName: "Mumbai",
        jsonRPC: "https://matic-mumbai.chainstacklabs.com",
        chainId: 13881,
        symbol: "MATIC",
        blockExplorer: "https://mumbai.polygonscan.com",
    },
    a86a: {
        netName: "Avalanche C-Chain",
        jsonRPC: "https://api.avax.network/ext/bc/C/rpc",
        chainId: "a86a",
        symbol: "AVAX",
        blockExplorer: "https://snowtrace.io",
    },
    a869: {
        netName: "Avalanche Fuji Testnet",
        jsonRPC: "https://api.avax-test.network/ext/bc/C/rpc",
        chainId: "a869",
        symbol: "AVAX",
        blockExplorer: "https://testnet.snowtrace.io",
    },
    fa: {
        netName: "Fantom Opera",
        jsonRPC: "https://rpc.ftm.tools",
        chainId: "fa",
        symbol: "FTM",
        blockExplorer: "https://ftmscan.com",
    },
    fa2: {
        netName: "Fantom Testnet",
        jsonRPC: "https://rpc.testnet.fantom.network",
        chainId: "fa2",
        symbol: "FTM",
        blockExplorer: "https://testnet.ftmscan.com",
    },
}